# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device//tenderloin/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/hp/tenderloin/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/hp/tenderloin/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/hp/tenderloin/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/hp/tenderloin/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/hp/tenderloin/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/hp/tenderloin/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/hp/tenderloin/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/hp/tenderloin/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/libc2d2_z180.so:system/vendor/lib/libc2d2_z180.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/libOpenVG.so:system/vendor/lib/libOpenVG.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/egl/libGLESv2S3D_adreno.so:system/vendor/lib/egl/libGLESv2S3D_adreno.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/hp/tenderloin/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/hp/tenderloin/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/hp/tenderloin/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/hp/tenderloin/proprietary/etc/firmware/a6_1.txt:system/etc/firmware/a6_1.txt \
    vendor/hp/tenderloin/proprietary/etc/firmware/a6.txt:system/etc/firmware/a6.txt \
    vendor/hp/tenderloin/proprietary/etc/firmware/q6.b00:system/etc/firmware/q6.b00 \
    vendor/hp/tenderloin/proprietary/etc/firmware/q6.b01:system/etc/firmware/q6.b01 \
    vendor/hp/tenderloin/proprietary/etc/firmware/q6.b02:system/etc/firmware/q6.b02 \
    vendor/hp/tenderloin/proprietary/etc/firmware/q6.b03:system/etc/firmware/q6.b03 \
    vendor/hp/tenderloin/proprietary/etc/firmware/q6.b04:system/etc/firmware/q6.b04 \
    vendor/hp/tenderloin/proprietary/etc/firmware/q6.b05:system/etc/firmware/q6.b05 \
    vendor/hp/tenderloin/proprietary/etc/firmware/q6.mdt:system/etc/firmware/q6.mdt \
    vendor/hp/tenderloin/proprietary/etc/firmware/wm8958_mbc.wfw:system/etc/firmware/wm8958_mbc.wfw \
    vendor/hp/tenderloin/proprietary/etc/firmware/wm8958_mbc_vss.wfw:system/etc/firmware/wm8958_mbc_vss.wfw \
    vendor/hp/tenderloin/proprietary/etc/firmware/wm8958_enh_eq.wfw:system/etc/firmware/wm8958_enh_eq.wfw \
    vendor/hp/tenderloin/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/hp/tenderloin/proprietary/bin/thermald:system/bin/thermald \
    vendor/hp/tenderloin/proprietary/etc/thermald.conf:system/etc/thermald.conf

PRODUCT_COPY_FILES += \
    vendor/hp/tenderloin/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/hp/tenderloin/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so
