# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/hp/tenderloin/extract-files.sh

# Prelink
PRODUCT_COPY_FILES += \
    vendor/hp/tenderloin/proprietary/lib/libcamera.so:obj/lib/libcamera.so

# Shared Object Libraries
PRODUCT_COPY_FILES += \
    vendor/hp/tenderloin/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/hp/tenderloin/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/hp/tenderloin/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/hp/tenderloin/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/hp/tenderloin/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/hp/tenderloin/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/hp/tenderloin/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/hp/tenderloin/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/hp/tenderloin/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so 

#EGL
PRODUCT_COPY_FILES += \
    vendor/hp/tenderloin/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/hp/tenderloin/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/hp/tenderloin/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/hp/tenderloin/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so

#HW
PRODUCT_COPY_FILES += \
    vendor/hp/tenderloin/proprietary/lib/hw/lights.msm8660.so:system/lib/hw/lights.msm8660.so 

#BIN
PRODUCT_COPY_FILES += \
    vendor/hp/tenderloin/proprietary/bin/battery_charging:system/bin/battery_charging \
    vendor/hp/tenderloin/proprietary/bin/dcvs:system/bin/dcvs \
    vendor/hp/tenderloin/proprietary/bin/dcvsd:system/bin/dcvsd \
    vendor/hp/tenderloin/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/hp/tenderloin/proprietary/bin/mpld:system/bin/mpld \
    vendor/hp/tenderloin/proprietary/bin/sensord:system/bin/sensord \
    vendor/hp/tenderloin/proprietary/bin/thermald:system/bin/thermald \
    vendor/hp/tenderloin/proprietary/bin/usbhub:system/bin/usbhub \
    vendor/hp/tenderloin/proprietary/bin/usbhub_init:system/bin/usbhub_init 

#Firmware
PRODUCT_COPY_FILES += \
	vendor/hp/tenderloin/proprietary/etc/firmware/leia_pfp_470.fw:/system/etc/firmware/leia_pfp_470.fw \
	vendor/hp/tenderloin/proprietary/etc/firmware/leia_pm4_470.fw:/system/etc/firmware/leia_pm4_470.fw \
	vendor/hp/tenderloin/proprietary/etc/firmware/vidc_1080p.fw:/system/etc/firmware/vidc_1080p.fw \
	vendor/hp/tenderloin/proprietary/etc/firmware/yamato_pfp.fw:/system/etc/firmware/yamato_pfp.fw \
	vendor/hp/tenderloin/proprietary/etc/firmware/yamato_pm4.fw:/system/etc/firmware/yamato_pm4.fw 

